spring:
  flyway:
    locations: classpath:/db/migration
    check-location: true

  datasource:
    url: jdbc:h2:mem:demo_project;DB_CLOSE_DELAY=-1;
    driver-class-name: org.h2.Driver
    type: org.apache.tomcat.jdbc.pool.DataSource
    #username: h2user
    #password: h2pass

  jpa:
    hibernate:
      ddl-auto: validate
      