spring:
  flyway:
    locations: classpath:/db/migration
    check-location: true

  datasource:
    url: jdbc:migration:mem:demo-project;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
    driver-class-name: org.h2.Driver
    type: org.apache.tomcat.jdbc.pool.DataSource
    #username: h2user
    #password: h2pass

  jpa:
    hibernate:
      ddl-auto: none